name: torch-serve
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cudatoolkit=10.1.243
  - grpcio=1.27.2
  - intel-openmp=2020.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.1.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pip=20.0.2
  - protobuf=3.11.4
  - python=3.7.7
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - tk=8.6.8
  - toolz=0.10.0
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
